# Generated by Django 5.0.6 on 2024-05-31 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautiful_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
