# Generated by Django 5.0.6 on 2024-06-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautiful_chat', '0006_remove_userprofile_pic_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='/static/beautiful_chat/default_pfp.png', upload_to='profile_picture/'),
        ),
    ]
